### PR TITLE
Update MongodDB ServiceManager Release Note

### PR DESCRIPTION
**Pull request by frbimo**
This PR updates MongodDB ServiceManager Release Note on
/Databases/MongoDB/MongoDB_ServiceManager_ReleaseNote_en.md

### CODE REVIEW

**Comment by ginneyeh** [comment]
請忽略此replease note，需要保留上架版本資訊

**Comment by frbimo** [comment]
@ginneyeh updated.

**Comment by frbimo** [comment]
supercede #49

**Pull request closed without merging**
